[tool.briefcase]
project_name = "MoodApp"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/moodapp"
license = "BSD license"
author = 'Mateusz Ogrodowczyk'
author_email = "matjonne@gmail.com"

[tool.briefcase.app.moodapp]
formal_name = "MoodApp"
description = "Recruitment test application using FB api"
icon = "src/moodapp/resources/moodapp"
sources = ['src/moodapp']
requires = []


[tool.briefcase.app.moodapp.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.moodapp.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.moodapp.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.moodapp.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.moodapp.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
